/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Options {
  /**
   * Strip trailing commas in addition to comments.
   * @default false
   */
  trailingCommas?: boolean
  /**
   * Replace comments and trailing commas with whitespace instead of stripping them entirely.
   * @default true
   */
  whitespace?: boolean
}

/**
 * Strip comments from JSON. Lets you use comments in your JSON files!
 *
 * It will replace single-line comments and multi-line comments with whitespace.
 * This allows JSON error positions to remain as close as possible to the original source.
 *
 * # Example
 *
 *    const stripJsonComments = require('@native/strip-json-comments-rs');
 *    const json = '{//rainbows//"unicorn":"cake"}';
 *    JSON.parse(stripJsonComments(json));
 *    //=> {unicorn: 'cake'}
 *
 * # Errors
 *
 * Returns Err if NAPI value conversion fails (should not occur in normal usage).
 * The function itself does not validate JSON syntax.
 *
 * # NAPI Constraint
 *
 * The function signature uses String instead of &str because NAPI-RS removed
 * &str `FromNapiValue` in v3.0.0-alpha.16. This is required for JS interop.
 *
 * # Safety
 *
 * Internally uses unsafe for the final UTF-8 conversion. This is safe because:
 * - Input is guaranteed valid UTF-8 (comes from JS String)
 * - We only modify ASCII bytes (comments, whitespace, commas)
 * - All UTF-8 multi-byte sequences are preserved unchanged
 */
export declare function stripJsonComments(jsonString: string, options?: Options | undefined | null): string
